// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/jeffleon2/draftea-wallet-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockWalletRepo is an autogenerated mock type for the WalletRepo type
type MockWalletRepo struct {
	mock.Mock
}

type MockWalletRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepo) EXPECT() *MockWalletRepo_Expecter {
	return &MockWalletRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, payment
func (_m *MockWalletRepo) Create(ctx context.Context, payment *models.Wallet) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Wallet) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWalletRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *models.Wallet
func (_e *MockWalletRepo_Expecter) Create(ctx interface{}, payment interface{}) *MockWalletRepo_Create_Call {
	return &MockWalletRepo_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockWalletRepo_Create_Call) Run(run func(ctx context.Context, payment *models.Wallet)) *MockWalletRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Wallet))
	})
	return _c
}

func (_c *MockWalletRepo_Create_Call) Return(_a0 error) *MockWalletRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepo_Create_Call) RunAndReturn(run func(context.Context, *models.Wallet) error) *MockWalletRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWalletRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWalletRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWalletRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockWalletRepo_Delete_Call {
	return &MockWalletRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWalletRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockWalletRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWalletRepo_Delete_Call) Return(_a0 error) *MockWalletRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepo_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockWalletRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockWalletRepo) GetAll(ctx context.Context) (*[]models.Wallet, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]models.Wallet, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]models.Wallet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWalletRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWalletRepo_Expecter) GetAll(ctx interface{}) *MockWalletRepo_GetAll_Call {
	return &MockWalletRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockWalletRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockWalletRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWalletRepo_GetAll_Call) Return(_a0 *[]models.Wallet, _a1 error) *MockWalletRepo_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_GetAll_Call) RunAndReturn(run func(context.Context) (*[]models.Wallet, error)) *MockWalletRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBy provides a mock function with given fields: ctx, key, value
func (_m *MockWalletRepo) GetBy(ctx context.Context, key string, value interface{}) (*[]models.Wallet, error) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetBy")
	}

	var r0 *[]models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (*[]models.Wallet, error)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) *[]models.Wallet); ok {
		r0 = rf(ctx, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_GetBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBy'
type MockWalletRepo_GetBy_Call struct {
	*mock.Call
}

// GetBy is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
func (_e *MockWalletRepo_Expecter) GetBy(ctx interface{}, key interface{}, value interface{}) *MockWalletRepo_GetBy_Call {
	return &MockWalletRepo_GetBy_Call{Call: _e.mock.On("GetBy", ctx, key, value)}
}

func (_c *MockWalletRepo_GetBy_Call) Run(run func(ctx context.Context, key string, value interface{})) *MockWalletRepo_GetBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockWalletRepo_GetBy_Call) Return(_a0 *[]models.Wallet, _a1 error) *MockWalletRepo_GetBy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_GetBy_Call) RunAndReturn(run func(context.Context, string, interface{}) (*[]models.Wallet, error)) *MockWalletRepo_GetBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWalletRepo) GetByID(ctx context.Context, id string) (*models.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWalletRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWalletRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockWalletRepo_GetByID_Call {
	return &MockWalletRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWalletRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockWalletRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWalletRepo_GetByID_Call) Return(_a0 *models.Wallet, _a1 error) *MockWalletRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.Wallet, error)) *MockWalletRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, wallet, id
func (_m *MockWalletRepo) Update(ctx context.Context, wallet *models.Wallet, id string) error {
	ret := _m.Called(ctx, wallet, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Wallet, string) error); ok {
		r0 = rf(ctx, wallet, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWalletRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - wallet *models.Wallet
//   - id string
func (_e *MockWalletRepo_Expecter) Update(ctx interface{}, wallet interface{}, id interface{}) *MockWalletRepo_Update_Call {
	return &MockWalletRepo_Update_Call{Call: _e.mock.On("Update", ctx, wallet, id)}
}

func (_c *MockWalletRepo_Update_Call) Run(run func(ctx context.Context, wallet *models.Wallet, id string)) *MockWalletRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Wallet), args[2].(string))
	})
	return _c
}

func (_c *MockWalletRepo_Update_Call) Return(_a0 error) *MockWalletRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepo_Update_Call) RunAndReturn(run func(context.Context, *models.Wallet, string) error) *MockWalletRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepo creates a new instance of MockWalletRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepo {
	mock := &MockWalletRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
