// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/jeffleon2/draftea-payment-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepo is an autogenerated mock type for the PaymentRepo type
type MockPaymentRepo struct {
	mock.Mock
}

type MockPaymentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepo) EXPECT() *MockPaymentRepo_Expecter {
	return &MockPaymentRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepo) Create(ctx context.Context, payment *models.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *models.Payment
func (_e *MockPaymentRepo_Expecter) Create(ctx interface{}, payment interface{}) *MockPaymentRepo_Create_Call {
	return &MockPaymentRepo_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepo_Create_Call) Run(run func(ctx context.Context, payment *models.Payment)) *MockPaymentRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Payment))
	})
	return _c
}

func (_c *MockPaymentRepo_Create_Call) Return(_a0 error) *MockPaymentRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_Create_Call) RunAndReturn(run func(context.Context, *models.Payment) error) *MockPaymentRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPaymentRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPaymentRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockPaymentRepo_Delete_Call {
	return &MockPaymentRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPaymentRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockPaymentRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_Delete_Call) Return(_a0 error) *MockPaymentRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockPaymentRepo) GetAll(ctx context.Context) (*[]models.Payment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]models.Payment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]models.Payment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPaymentRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentRepo_Expecter) GetAll(ctx interface{}) *MockPaymentRepo_GetAll_Call {
	return &MockPaymentRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockPaymentRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockPaymentRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentRepo_GetAll_Call) Return(_a0 *[]models.Payment, _a1 error) *MockPaymentRepo_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_GetAll_Call) RunAndReturn(run func(context.Context) (*[]models.Payment, error)) *MockPaymentRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepo) GetByID(ctx context.Context, id string) (*models.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPaymentRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPaymentRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockPaymentRepo_GetByID_Call {
	return &MockPaymentRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPaymentRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockPaymentRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_GetByID_Call) Return(_a0 *models.Payment, _a1 error) *MockPaymentRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.Payment, error)) *MockPaymentRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, payment, id
func (_m *MockPaymentRepo) Update(ctx context.Context, payment *models.Payment, id string) error {
	ret := _m.Called(ctx, payment, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Payment, string) error); ok {
		r0 = rf(ctx, payment, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPaymentRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *models.Payment
//   - id string
func (_e *MockPaymentRepo_Expecter) Update(ctx interface{}, payment interface{}, id interface{}) *MockPaymentRepo_Update_Call {
	return &MockPaymentRepo_Update_Call{Call: _e.mock.On("Update", ctx, payment, id)}
}

func (_c *MockPaymentRepo_Update_Call) Run(run func(ctx context.Context, payment *models.Payment, id string)) *MockPaymentRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Payment), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_Update_Call) Return(_a0 error) *MockPaymentRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_Update_Call) RunAndReturn(run func(context.Context, *models.Payment, string) error) *MockPaymentRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepo creates a new instance of MockPaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepo {
	mock := &MockPaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
