// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/jeffleon2/draftea-fraud-service/internal/models"
)

// MockFraudServiceIn is an autogenerated mock type for the FraudServiceIn type
type MockFraudServiceIn struct {
	mock.Mock
}

type MockFraudServiceIn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFraudServiceIn) EXPECT() *MockFraudServiceIn_Expecter {
	return &MockFraudServiceIn_Expecter{mock: &_m.Mock}
}

// EvaluatePayment provides a mock function with given fields: _a0, _a1
func (_m *MockFraudServiceIn) EvaluatePayment(_a0 context.Context, _a1 models.PaymentCreatedEvent) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EvaluatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.PaymentCreatedEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFraudServiceIn_EvaluatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluatePayment'
type MockFraudServiceIn_EvaluatePayment_Call struct {
	*mock.Call
}

// EvaluatePayment is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.PaymentCreatedEvent
func (_e *MockFraudServiceIn_Expecter) EvaluatePayment(_a0 interface{}, _a1 interface{}) *MockFraudServiceIn_EvaluatePayment_Call {
	return &MockFraudServiceIn_EvaluatePayment_Call{Call: _e.mock.On("EvaluatePayment", _a0, _a1)}
}

func (_c *MockFraudServiceIn_EvaluatePayment_Call) Run(run func(_a0 context.Context, _a1 models.PaymentCreatedEvent)) *MockFraudServiceIn_EvaluatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.PaymentCreatedEvent))
	})
	return _c
}

func (_c *MockFraudServiceIn_EvaluatePayment_Call) Return(_a0 error) *MockFraudServiceIn_EvaluatePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFraudServiceIn_EvaluatePayment_Call) RunAndReturn(run func(context.Context, models.PaymentCreatedEvent) error) *MockFraudServiceIn_EvaluatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFraudServiceIn creates a new instance of MockFraudServiceIn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFraudServiceIn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFraudServiceIn {
	mock := &MockFraudServiceIn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
